/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test;
import java.sql.ResultSet;
import java.sql.Statement;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import static test.Register.nama;
import static test.Register.simpan_nama;
import static test.Register.skor;

/**
 *
 * @author user
 */
public class Soal extends javax.swing.JFrame {
    koneksi kon;
    Statement st;

    /**
     * Creates new form Soal
     */
    public static int limit=3;
    public Soal() {
        initComponents();
        kon = new koneksi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jTextField8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jTextField10 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jTextField11 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jTextField12 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jTextField13 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jTextField14 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jTextField15 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jTextField17 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jTextField18 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jTextField19 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        jTextField20 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jTextField21 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jTextField22 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jTextField23 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Questions");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/29.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 140, 40));

        jTextField1.setText("jTextField1");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 210, 40));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setBackground(new java.awt.Color(249, 179, 71));
        jTextField2.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Answer");
        jTextField2.setBorder(null);
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 210, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/2.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField3.setBackground(new java.awt.Color(249, 179, 71));
        jTextField3.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("Answer");
        jTextField3.setBorder(null);
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 210, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/3.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField4.setBackground(new java.awt.Color(249, 179, 71));
        jTextField4.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("Answer");
        jTextField4.setBorder(null);
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });
        jPanel4.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 210, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/4.png"))); // NOI18N
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField5.setBackground(new java.awt.Color(249, 179, 71));
        jTextField5.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("Answer");
        jTextField5.setBorder(null);
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });
        jPanel5.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 210, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/5.png"))); // NOI18N
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField6.setBackground(new java.awt.Color(249, 179, 71));
        jTextField6.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("Answer");
        jTextField6.setBorder(null);
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
        });
        jPanel6.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 210, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/6.png"))); // NOI18N
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField7.setBackground(new java.awt.Color(249, 179, 71));
        jTextField7.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("Answer");
        jTextField7.setBorder(null);
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
        });
        jPanel7.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 210, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/7.png"))); // NOI18N
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField8.setBackground(new java.awt.Color(249, 179, 71));
        jTextField8.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("Answer");
        jTextField8.setBorder(null);
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField8KeyPressed(evt);
            }
        });
        jPanel8.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 210, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/8.png"))); // NOI18N
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 130, 130));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/30.png"))); // NOI18N
        jPanel9.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        jTextField9.setText("jTextField1");
        jPanel9.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 210, 40));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField10.setBackground(new java.awt.Color(249, 179, 71));
        jTextField10.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jTextField10.setForeground(new java.awt.Color(255, 255, 255));
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("Answer");
        jTextField10.setBorder(null);
        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField10KeyPressed(evt);
            }
        });
        jPanel10.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 210, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/9.png"))); // NOI18N
        jPanel10.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField11.setBackground(new java.awt.Color(249, 179, 71));
        jTextField11.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jTextField11.setForeground(new java.awt.Color(255, 255, 255));
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField11.setText("Answer");
        jTextField11.setBorder(null);
        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField11KeyPressed(evt);
            }
        });
        jPanel11.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 210, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/10.png"))); // NOI18N
        jPanel11.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField12.setBackground(new java.awt.Color(249, 179, 71));
        jTextField12.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jTextField12.setForeground(new java.awt.Color(255, 255, 255));
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField12.setText("Answer");
        jTextField12.setBorder(null);
        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField12KeyPressed(evt);
            }
        });
        jPanel12.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 210, 20));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/11.png"))); // NOI18N
        jPanel12.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField13.setBackground(new java.awt.Color(249, 179, 71));
        jTextField13.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jTextField13.setForeground(new java.awt.Color(255, 255, 255));
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField13.setText("Answer");
        jTextField13.setBorder(null);
        jTextField13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField13KeyPressed(evt);
            }
        });
        jPanel13.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 210, 20));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/14.png"))); // NOI18N
        jPanel13.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField14.setBackground(new java.awt.Color(249, 179, 71));
        jTextField14.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jTextField14.setForeground(new java.awt.Color(255, 255, 255));
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField14.setText("Answer");
        jTextField14.setBorder(null);
        jTextField14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField14KeyPressed(evt);
            }
        });
        jPanel14.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 210, 20));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/15.png"))); // NOI18N
        jPanel14.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField15.setBackground(new java.awt.Color(249, 179, 71));
        jTextField15.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jTextField15.setForeground(new java.awt.Color(255, 255, 255));
        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField15.setText("Answer");
        jTextField15.setBorder(null);
        jTextField15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField15KeyPressed(evt);
            }
        });
        jPanel15.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 210, 20));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/16.png"))); // NOI18N
        jPanel15.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        jPanel16.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 660, 460));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/31.png"))); // NOI18N
        jPanel16.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        jTextField16.setText("jTextField1");
        jPanel16.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 210, 40));

        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField17.setBackground(new java.awt.Color(249, 179, 71));
        jTextField17.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jTextField17.setForeground(new java.awt.Color(255, 255, 255));
        jTextField17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField17.setText("Answer");
        jTextField17.setBorder(null);
        jTextField17.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField17KeyPressed(evt);
            }
        });
        jPanel17.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 210, 20));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/18.png"))); // NOI18N
        jPanel17.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField18.setBackground(new java.awt.Color(249, 179, 71));
        jTextField18.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jTextField18.setForeground(new java.awt.Color(255, 255, 255));
        jTextField18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField18.setText("Answer");
        jTextField18.setBorder(null);
        jTextField18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField18KeyPressed(evt);
            }
        });
        jPanel18.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 210, 20));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/20.png"))); // NOI18N
        jPanel18.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField19.setBackground(new java.awt.Color(249, 179, 71));
        jTextField19.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jTextField19.setForeground(new java.awt.Color(255, 255, 255));
        jTextField19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField19.setText("Answer");
        jTextField19.setBorder(null);
        jTextField19.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField19KeyPressed(evt);
            }
        });
        jPanel19.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 210, 20));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/22.png"))); // NOI18N
        jPanel19.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField20.setBackground(new java.awt.Color(249, 179, 71));
        jTextField20.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jTextField20.setForeground(new java.awt.Color(255, 255, 255));
        jTextField20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField20.setText("Answer");
        jTextField20.setBorder(null);
        jTextField20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField20KeyPressed(evt);
            }
        });
        jPanel20.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 210, 20));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/23.png"))); // NOI18N
        jPanel20.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField21.setBackground(new java.awt.Color(249, 179, 71));
        jTextField21.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jTextField21.setForeground(new java.awt.Color(255, 255, 255));
        jTextField21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField21.setText("Answer");
        jTextField21.setBorder(null);
        jTextField21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField21KeyPressed(evt);
            }
        });
        jPanel21.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 210, 20));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/25.png"))); // NOI18N
        jPanel21.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField22.setBackground(new java.awt.Color(249, 179, 71));
        jTextField22.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jTextField22.setForeground(new java.awt.Color(255, 255, 255));
        jTextField22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField22.setText("Answer");
        jTextField22.setBorder(null);
        jTextField22.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField22KeyPressed(evt);
            }
        });
        jPanel22.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 210, 20));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/27.png"))); // NOI18N
        jPanel22.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField23.setBackground(new java.awt.Color(249, 179, 71));
        jTextField23.setFont(new java.awt.Font("Ebrima", 1, 16)); // NOI18N
        jTextField23.setForeground(new java.awt.Color(255, 255, 255));
        jTextField23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField23.setText("Answer");
        jTextField23.setBorder(null);
        jTextField23.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField23KeyPressed(evt);
            }
        });
        jPanel23.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 210, 20));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/test/28.png"))); // NOI18N
        jPanel23.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        jPanel1.setVisible(false);
        jPanel2.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (limit>0 && jTextField2.getText().equalsIgnoreCase("kulkas")){
                jPanel2.setVisible(false);
                jPanel3.setVisible(true);
            }
            else if(limit!=0){
                --limit;
                JOptionPane.showMessageDialog(rootPane, "Jiakh salah !! \n"+limit+" kali kesempatan lagi yaa");
                jTextField2.getText();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Game over!\nLet's try again.");
                this.setVisible(false);
                new Register().setVisible(true);
            }
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (limit>0 && jTextField3.getText().equalsIgnoreCase("hansip")){
                jPanel3.setVisible(false);
                jPanel4.setVisible(true);
            }
            else if(limit!=0){
                --limit;
                JOptionPane.showMessageDialog(rootPane, "Jiakh salah !! \n"+limit+" kali kesempatan lagi yaa");
                jTextField3.getText();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Game over!\nLet's try again.");
                Register.skor=5;
                
               try {
                String daftar="insert into skor (username, skore) values ('"+simpan_nama+"','"+Register.skor+"')";
                st = kon.con.createStatement();
                st.executeUpdate(daftar);
        } catch (Exception e) {
        }
                this.setVisible(false);
                new Register().setVisible(true);
            }
        }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (limit>0 && jTextField4.getText().equalsIgnoreCase("karambol")){
                jPanel4.setVisible(false);
                jPanel5.setVisible(true);
            }
            else if(limit!=0){
                --limit;
                JOptionPane.showMessageDialog(rootPane, "Jiakh salah !! \n"+limit+" kali kesempatan lagi yaa");
                jTextField4.getText();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Game over!\nLet's try again.");
                Register.skor=10;
                
               try {
                String daftar="insert into skor (username, skore) values ('"+simpan_nama+"','"+Register.skor+"')";
                st = kon.con.createStatement();
                st.executeUpdate(daftar);
        } catch (Exception e) {
        }
                this.setVisible(false);
                new Register().setVisible(true);
            }
        }
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (limit>0 && jTextField5.getText().equalsIgnoreCase("pilus")){
                jPanel5.setVisible(false);
                jPanel6.setVisible(true);
            }
            else if(limit!=0){
                --limit;
                JOptionPane.showMessageDialog(rootPane, "Jiakh salah !! \n"+limit+" kali kesempatan lagi yaa");
                jTextField5.getText();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Game over!\nLet's try again.");
                Register.skor=15;
                
               try {
                String daftar="insert into skor (username, skore) values ('"+simpan_nama+"','"+Register.skor+"')";
                st = kon.con.createStatement();
                st.executeUpdate(daftar);
        } catch (Exception e) {
        }
                this.setVisible(false);
                new Register().setVisible(true);
            }
        }
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (limit>0 && jTextField6.getText().equalsIgnoreCase("gerindra")){
                jPanel6.setVisible(false);
                jPanel7.setVisible(true);
            }
            else if(limit!=0){
                --limit;
                JOptionPane.showMessageDialog(rootPane, "Jiakh salah !! \n"+limit+" kali kesempatan lagi yaa");
                jTextField6.getText();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Game over!\nLet's try again.");
                Register.skor=20;
                
               try {
                String daftar="insert into skor (username, skore) values ('"+simpan_nama+"','"+Register.skor+"')";
                st = kon.con.createStatement();
                st.executeUpdate(daftar);
        } catch (Exception e) {
        }
                this.setVisible(false);
                new Register().setVisible(true);
            }
        }
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (limit>0 && jTextField7.getText().equalsIgnoreCase("bakso")){
                jPanel7.setVisible(false);
                jPanel8.setVisible(true);
            }
            else if(limit!=0){
                --limit;
                JOptionPane.showMessageDialog(rootPane, "Jiakh salah !! \n"+limit+" kali kesempatan lagi yaa");
                jTextField7.getText();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Game over!\nLet's try again.");
                Register.skor=25;
                
               try {
                String daftar="insert into skor (username, skore) values ('"+simpan_nama+"','"+Register.skor+"')";
                st = kon.con.createStatement();
                st.executeUpdate(daftar);
        } catch (Exception e) {
        }
                this.setVisible(false);
                new Register().setVisible(true);
            }
        }
    }//GEN-LAST:event_jTextField7KeyPressed

    private void jTextField8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (limit>0 && jTextField8.getText().equalsIgnoreCase("delman")){
                jPanel8.setVisible(false);
                jPanel9.setVisible(true);
            }
            else if(limit!=0){
                --limit;
                JOptionPane.showMessageDialog(rootPane, "Jiakh salah !! \n"+limit+" kali kesempatan lagi yaa");
                jTextField8.getText();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Game over!\nLet's try again.");
                Register.skor=30;
                
               try {
                String daftar="insert into skor (username, skore) values ('"+simpan_nama+"','"+Register.skor+"')";
                st = kon.con.createStatement();
                st.executeUpdate(daftar);
        } catch (Exception e) {
        }
                this.setVisible(false);
                new Register().setVisible(true);
            }
        }
    }//GEN-LAST:event_jTextField8KeyPressed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        jPanel9.setVisible(false);
        jPanel10.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jTextField10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (limit>0 && jTextField10.getText().equalsIgnoreCase("pistol")){
                jPanel10.setVisible(false);
                jPanel11.setVisible(true);
            }
            else if(limit!=0){
                --limit;
                JOptionPane.showMessageDialog(rootPane, "Jiakh salah !! \n"+limit+" kali kesempatan lagi yaa");
                jTextField10.getText();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Game over!\nLet's try again.");
                Register.skor=40;
                
               try {
                String daftar="insert into skor (username, skore) values ('"+simpan_nama+"','"+Register.skor+"')";
                st = kon.con.createStatement();
                st.executeUpdate(daftar);
        } catch (Exception e) {
        }
                this.setVisible(false);
                new Register().setVisible(true);
            }
        }
    }//GEN-LAST:event_jTextField10KeyPressed

    private void jTextField11KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (limit>0 && jTextField11.getText().equalsIgnoreCase("jambret")){
                jPanel11.setVisible(false);
                jPanel12.setVisible(true);
            }
            else if(limit!=0){
                --limit;
                JOptionPane.showMessageDialog(rootPane, "Jiakh salah !! \n"+limit+" kali kesempatan lagi yaa");
                jTextField11.getText();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Game over!\nLet's try again.");
                Register.skor=50;
                
               try {
                String daftar="insert into skor (username, skore) values ('"+simpan_nama+"','"+Register.skor+"')";
                st = kon.con.createStatement();
                st.executeUpdate(daftar);
        } catch (Exception e) {
        }
                this.setVisible(false);
                new Register().setVisible(true);
            }
        }
    }//GEN-LAST:event_jTextField11KeyPressed

    private void jTextField12KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (limit>0 && jTextField12.getText().equalsIgnoreCase("megawati")){
                jPanel12.setVisible(false);
                jPanel13.setVisible(true);
            }
            else if(limit!=0){
                --limit;
                JOptionPane.showMessageDialog(rootPane, "Jiakh salah !! \n"+limit+" kali kesempatan lagi yaa");
                jTextField12.getText();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Game over!\nLet's try again.");
                Register.skor=60;
                
               try {
                String daftar="insert into skor (username, skore) values ('"+simpan_nama+"','"+Register.skor+"')";
                st = kon.con.createStatement();
                st.executeUpdate(daftar);
        } catch (Exception e) {
        }
                this.setVisible(false);
                new Register().setVisible(true);
            }
        }
    }//GEN-LAST:event_jTextField12KeyPressed

    private void jTextField13KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField13KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (limit>0 && jTextField13.getText().equalsIgnoreCase("limbad")){
                jPanel13.setVisible(false);
                jPanel14.setVisible(true);
            }
            else if(limit!=0){
                --limit;
                JOptionPane.showMessageDialog(rootPane, "Jiakh salah !! \n"+limit+" kali kesempatan lagi yaa");
                jTextField13.getText();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Game over!\nLet's try again.");
                Register.skor=70;
                
               try {
                String daftar="insert into skor (username, skore) values ('"+simpan_nama+"','"+Register.skor+"')";
                st = kon.con.createStatement();
                st.executeUpdate(daftar);
        } catch (Exception e) {
        }
                this.setVisible(false);
                new Register().setVisible(true);
            }
        }
    }//GEN-LAST:event_jTextField13KeyPressed

    private void jTextField14KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField14KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (limit>0 && jTextField14.getText().equalsIgnoreCase("komeng")){
                jPanel14.setVisible(false);
                jPanel15.setVisible(true);
            }
            else if(limit!=0){
                --limit;
                JOptionPane.showMessageDialog(rootPane, "Jiakh salah !! \n"+limit+" kali kesempatan lagi yaa");
                jTextField14.getText();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Game over!\nLet's try again.");
                Register.skor=80;
                
               try {
                String daftar="insert into skor (username, skore) values ('"+simpan_nama+"','"+Register.skor+"')";
                st = kon.con.createStatement();
                st.executeUpdate(daftar);
        } catch (Exception e) {
        }
                this.setVisible(false);
                new Register().setVisible(true);
            }
        }
    }//GEN-LAST:event_jTextField14KeyPressed

    private void jTextField15KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField15KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (limit>0 && jTextField15.getText().equalsIgnoreCase("alyssa soebandono")){
                jPanel15.setVisible(false);
                jPanel16.setVisible(true);
            }
            else if(limit!=0){
                --limit;
                JOptionPane.showMessageDialog(rootPane, "Jiakh salah !! \n"+limit+" kali kesempatan lagi yaa");
                jTextField15.getText();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Game over!\nLet's try again.");
                Register.skor=90;
                
               try {
                String daftar="insert into skor (username, skore) values ('"+simpan_nama+"','"+Register.skor+"')";
                st = kon.con.createStatement();
                st.executeUpdate(daftar);
        } catch (Exception e) {
        }
                this.setVisible(false);
                new Register().setVisible(true);
            }
        }
    }//GEN-LAST:event_jTextField15KeyPressed

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        jPanel16.setVisible(false);
        jPanel17.setVisible(true);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jTextField17KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField17KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (limit>0 && jTextField17.getText().equalsIgnoreCase("shireen sungkar")){
                jPanel17.setVisible(false);
                jPanel18.setVisible(true);
            }
            else if(limit!=0){
                --limit;
                JOptionPane.showMessageDialog(rootPane, "Jiakh salah !! \n"+limit+" kali kesempatan lagi yaa");
                jTextField17.getText();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Game over!\nLet's try again.");
                Register.skor=105;
                
               try {
                String daftar="insert into skor (username, skore) values ('"+simpan_nama+"','"+Register.skor+"')";
                st = kon.con.createStatement();
                st.executeUpdate(daftar);
        } catch (Exception e) {
        }
                this.setVisible(false);
                new Register().setVisible(true);
            }
        }
    }//GEN-LAST:event_jTextField17KeyPressed

    private void jTextField18KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField18KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (limit>0 && jTextField18.getText().equalsIgnoreCase("tora sudiro")){
                jPanel18.setVisible(false);
                jPanel19.setVisible(true);
            }
            else if(limit!=0){
                --limit;
                JOptionPane.showMessageDialog(rootPane, "Jiakh salah !! \n"+limit+" kali kesempatan lagi yaa");
                jTextField18.getText();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Game over!\nLet's try again.");
                Register.skor=120;
                
               try {
                String daftar="insert into skor (username, skore) values ('"+simpan_nama+"','"+Register.skor+"')";
                st = kon.con.createStatement();
                st.executeUpdate(daftar);
        } catch (Exception e) {
        }
                this.setVisible(false);
                new Register().setVisible(true);
            }
        }
    }//GEN-LAST:event_jTextField18KeyPressed

    private void jTextField19KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField19KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (limit>0 && jTextField19.getText().equalsIgnoreCase("beyonce")){
                jPanel19.setVisible(false);
                jPanel20.setVisible(true);
            }
            else if(limit!=0){
                --limit;
                JOptionPane.showMessageDialog(rootPane, "Jiakh salah !! \n"+limit+" kali kesempatan lagi yaa");
                jTextField19.getText();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Game over!\nLet's try again.");
                Register.skor=135;
                
               try {
                String daftar="insert into skor (username, skore) values ('"+simpan_nama+"','"+Register.skor+"')";
                st = kon.con.createStatement();
                st.executeUpdate(daftar);
        } catch (Exception e) {
        }
                this.setVisible(false);
                new Register().setVisible(true);
            }
        }
    }//GEN-LAST:event_jTextField19KeyPressed

    private void jTextField20KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField20KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (limit>0 && jTextField20.getText().equalsIgnoreCase("jackie chan")){
                jPanel20.setVisible(false);
                jPanel21.setVisible(true);
            }
            else if(limit!=0){
                --limit;
                JOptionPane.showMessageDialog(rootPane, "Jiakh salah !! \n"+limit+" kali kesempatan lagi yaa");
                jTextField20.getText();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Game over!\nLet's try again.");
                Register.skor=150;
                
               try {
                String daftar="insert into skor (username, skore) values ('"+simpan_nama+"','"+Register.skor+"')";
                st = kon.con.createStatement();
                st.executeUpdate(daftar);
        } catch (Exception e) {
        }
                this.setVisible(false);
                new Register().setVisible(true);
            }
        }
    }//GEN-LAST:event_jTextField20KeyPressed

    private void jTextField21KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField21KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (limit>0 && jTextField21.getText().equalsIgnoreCase("mario teguh")){
                jPanel21.setVisible(false);
                jPanel22.setVisible(true);
            }
            else if(limit!=0){
                --limit;
                JOptionPane.showMessageDialog(rootPane, "Jiakh salah !! \n"+limit+" kali kesempatan lagi yaa");
                jTextField21.getText();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Game over!\nLet's try again.");
                Register.skor=165;
                
               try {
                String daftar="insert into skor (username, skore) values ('"+simpan_nama+"','"+Register.skor+"')";
                st = kon.con.createStatement();
                st.executeUpdate(daftar);
        } catch (Exception e) {
        }
                this.setVisible(false);
                new Register().setVisible(true);
            }
        }
    }//GEN-LAST:event_jTextField21KeyPressed

    private void jTextField22KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField22KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (limit>0 && jTextField22.getText().equalsIgnoreCase("nicholas saputra")){
                jPanel22.setVisible(false);
                jPanel23.setVisible(true);
            }
            else if(limit!=0){
                --limit;
                JOptionPane.showMessageDialog(rootPane, "Jiakh salah !! \n"+limit+" kali kesempatan lagi yaa");
                jTextField22.getText();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Game over!\nLet's try again.");
                Register.skor=180;
                
               try {
                String daftar="insert into skor (username, skore) values ('"+simpan_nama+"','"+Register.skor+"')";
                st = kon.con.createStatement();
                st.executeUpdate(daftar);
        } catch (Exception e) {
        }
                this.setVisible(false);
                new Register().setVisible(true);
            }
        }
    }//GEN-LAST:event_jTextField22KeyPressed

    private void jTextField23KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField23KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if (limit>0 && jTextField23.getText().equalsIgnoreCase("baim wong")){
                jPanel23.setVisible(false);
                this.setVisible(false);
                new Finish().setVisible(true);
                Register.skor=200;
                try {
                String daftar="insert into skor (username, skore) values ('"+simpan_nama+"','"+Register.skor+"')";
                st = kon.con.createStatement();
                st.executeUpdate(daftar);
        } catch (Exception e) {
        }
                this.setVisible(false);
                new Finish().setVisible(true);
            }
            else if(limit!=0){
                --limit;
                JOptionPane.showMessageDialog(rootPane, "Jiakh salah !! \n"+limit+" kali kesempatan lagi yaa");
                jTextField23.getText();
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Game over!\nLet's try again.");
                Register.skor=180;
                
               try {
                String daftar="insert into skor (username, skore) values ('"+simpan_nama+"','"+Register.skor+"')";
                st = kon.con.createStatement();
                st.executeUpdate(daftar);
        } catch (Exception e) {
        }
                this.setVisible(false);
                new Register().setVisible(true);
            }
        }
    }//GEN-LAST:event_jTextField23KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Soal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Soal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Soal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Soal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Soal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
